export { default as Landing } from './Landing'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as NotFound } from './NotFound'
export { default as User } from './User'
export { default as Home } from './Home'
export { default as Chat } from './Chat'